/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Gastos;

import AccesoDatos.*;
import Entidades.Gasto;
import java.awt.Toolkit;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.time.format.DateTimeParseException;
import javax.swing.JOptionPane;

/**
 *
 * @author Pato
 */
public class ModificarGasto extends javax.swing.JFrame {

    private Gasto gastoActual;
    private GastoData gastoData = new GastoData();
    
    
    public ModificarGasto(Gasto gasto) {
        initComponents();
        
        this.gastoActual = gasto;
        cargarCategorias();
        cargarDatos();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Llave.png")));
        setLocationRelativeTo(null);
        this.setTitle("Modificar Gasto");
        
        aplicarEstiloBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtFecha = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jcbCategoria = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtDescripcion = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtObservacion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jtMonto = new javax.swing.JTextField();
        jbGuardar = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setText("Modificar Gasto");

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 220, 220));
        jLabel1.setText("Fecha:");

        jtFecha.setBackground(new java.awt.Color(50, 50, 50));
        jtFecha.setForeground(new java.awt.Color(220, 220, 220));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 220, 220));
        jLabel3.setText("Categoria:");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(220, 220, 220));
        jLabel4.setText("Descripcion:");

        jtDescripcion.setBackground(new java.awt.Color(50, 50, 50));
        jtDescripcion.setForeground(new java.awt.Color(220, 220, 220));

        jLabel5.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(220, 220, 220));
        jLabel5.setText("Observacion:");

        jtObservacion.setBackground(new java.awt.Color(50, 50, 50));
        jtObservacion.setForeground(new java.awt.Color(220, 220, 220));

        jLabel6.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(220, 220, 220));
        jLabel6.setText("Monto:");

        jtMonto.setBackground(new java.awt.Color(50, 50, 50));
        jtMonto.setForeground(new java.awt.Color(220, 220, 220));

        jbGuardar.setBackground(new java.awt.Color(50, 50, 50));
        jbGuardar.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jbGuardar.setForeground(new java.awt.Color(0, 204, 102));
        jbGuardar.setText("Guardar");
        jbGuardar.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jbGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarActionPerformed(evt);
            }
        });

        jbVolver.setBackground(new java.awt.Color(50, 50, 50));
        jbVolver.setFont(new java.awt.Font("Dialog", 0, 13)); // NOI18N
        jbVolver.setForeground(new java.awt.Color(255, 102, 0));
        jbVolver.setText("Volver");
        jbVolver.setBorder(null);
        jbVolver.setBorderPainted(false);
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(281, 281, 281)
                        .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(163, 163, 163))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(58, 58, 58)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcbCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtObservacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtMonto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(jbGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarActionPerformed

            try {

            String fechaTexto = jtFecha.getText().trim();
            String categoria = jcbCategoria.getSelectedItem().toString();
            String descripcion = jtDescripcion.getText().trim();
            String montoTexto = jtMonto.getText().trim();
            String observacion = jtObservacion.getText().trim();

            if (fechaTexto.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese la fecha.");
                return;
            }

            if (descripcion.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese una descripción.");
                return;
            }

            if (montoTexto.isEmpty()) {
                JOptionPane.showMessageDialog(null, "Ingrese el monto.");
                return;
            }

            int monto = Integer.parseInt(montoTexto);

            if (monto <= 0) {
                JOptionPane.showMessageDialog(null, "El monto debe ser mayor a 0.");
                return;
            }

            DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            LocalDate fecha = LocalDate.parse(fechaTexto, formato);

            LocalDateTime fechaGasto = fecha.atStartOfDay();

            gastoActual.setFecha(fechaGasto);
            gastoActual.setCategoria(categoria);
            gastoActual.setDescripcion(descripcion);
            gastoActual.setMonto(monto);
            gastoActual.setObservacion(observacion);

            gastoData.modificarGasto(gastoActual);

            VerGastos ver = new VerGastos();
            ver.setVisible(true);

            this.dispose();

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(null, "El monto debe ser un número válido.");

        } catch (DateTimeParseException ex) {

            JOptionPane.showMessageDialog(
                null,
                "La fecha debe tener el formato dd/MM/yyyy. Ejemplo: 08/07/2026"
            );
        }

    }//GEN-LAST:event_jbGuardarActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed

        VerGastos ver = new VerGastos();
        ver.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    
    
    
    private void cargarCategorias() {

    jcbCategoria.removeAllItems();

    jcbCategoria.addItem("Alquiler");
    jcbCategoria.addItem("Luz");
    jcbCategoria.addItem("Agua");
    jcbCategoria.addItem("Internet");
    jcbCategoria.addItem("Nafta");
    jcbCategoria.addItem("Herramientas");
    jcbCategoria.addItem("Insumos");
    jcbCategoria.addItem("Limpieza");
    jcbCategoria.addItem("Comida");
    jcbCategoria.addItem("Varios");
}
    
    
    
    
    private void cargarDatos() {

    DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy");

    jtFecha.setText(gastoActual.getFecha().format(formato));

    jcbCategoria.setSelectedItem(gastoActual.getCategoria());

    jtDescripcion.setText(gastoActual.getDescripcion());
    jtMonto.setText(String.valueOf(gastoActual.getMonto()));
    jtObservacion.setText(gastoActual.getObservacion());
}
    
    
    
    
    private void aplicarEstiloBotones() {

    // Botones verdes - acciones positivas
    jbGuardar.setBackground(new java.awt.Color(60, 130, 70));
    jbGuardar.setForeground(java.awt.Color.WHITE);

    // Botones grises - navegación
    jbVolver.setBackground(new java.awt.Color(70, 70, 70));
    jbVolver.setForeground(java.awt.Color.WHITE);
}
    
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbGuardar;
    private javax.swing.JButton jbVolver;
    private javax.swing.JComboBox<String> jcbCategoria;
    private javax.swing.JTextField jtDescripcion;
    private javax.swing.JTextField jtFecha;
    private javax.swing.JTextField jtMonto;
    private javax.swing.JTextField jtObservacion;
    // End of variables declaration//GEN-END:variables
}
