package Vistas.Gastos;

import AccesoDatos.GastoData;
import Entidades.Gasto;
import Vistas.Menu;
import java.awt.Toolkit;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VerGastos extends javax.swing.JFrame {

    
    private GastoData gastoData = new GastoData();

private DefaultTableModel modeloGastos = new DefaultTableModel() {

    @Override
    public boolean isCellEditable(int fila, int columna) {
        return false;
    }
};
    
    
    public VerGastos() {
        initComponents();
        
        armarCabeceraGastos();
        cargarCombosFecha();
        seleccionarTodos();
        cargarGastos();
        
        aplicarEstiloTabla();
        aplicarEstiloBotones();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Llave.png")));
        setLocationRelativeTo(null);
        this.setTitle("Ver Gastos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jcbMes = new javax.swing.JComboBox<>();
        jcbAnio = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCompras = new javax.swing.JTable();
        jbNuevoGasto = new javax.swing.JButton();
        jbModificarGasto = new javax.swing.JButton();
        jbAnular = new javax.swing.JButton();
        jbMenu = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));
        jPanel1.setPreferredSize(new java.awt.Dimension(852, 806));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setText("Gastos del Taller");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(200, 200, 200));
        jLabel8.setText("Mes:");

        jcbMes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbMesActionPerformed(evt);
            }
        });

        jcbAnio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcbAnioActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(200, 200, 200));
        jLabel9.setText("Año:");

        TablaCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaComprasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCompras);

        jbNuevoGasto.setBackground(new java.awt.Color(5, 5, 5));
        jbNuevoGasto.setForeground(new java.awt.Color(0, 153, 204));
        jbNuevoGasto.setText("Nuevo Gasto");
        jbNuevoGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoGastoActionPerformed(evt);
            }
        });

        jbModificarGasto.setBackground(new java.awt.Color(5, 5, 5));
        jbModificarGasto.setForeground(new java.awt.Color(0, 153, 204));
        jbModificarGasto.setText("Modificar Gasto");
        jbModificarGasto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarGastoActionPerformed(evt);
            }
        });

        jbAnular.setBackground(new java.awt.Color(5, 5, 5));
        jbAnular.setForeground(new java.awt.Color(0, 153, 204));
        jbAnular.setText("Anular Gasto");
        jbAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularActionPerformed(evt);
            }
        });

        jbMenu.setBackground(new java.awt.Color(5, 5, 5));
        jbMenu.setForeground(new java.awt.Color(204, 102, 0));
        jbMenu.setText("Volver al Menu");
        jbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(220, 220, 220));
        jLabel11.setText("Total mostrado:");

        jtTotal.setEditable(false);
        jtTotal.setBackground(new java.awt.Color(50, 50, 50));
        jtTotal.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jtTotal.setForeground(new java.awt.Color(204, 204, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(253, 253, 253)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGap(3, 3, 3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jbNuevoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(44, 44, 44)
                                    .addComponent(jbModificarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(50, 50, 50)
                                    .addComponent(jbAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addComponent(jLabel11)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(231, 231, 231))))))
                .addGap(94, 94, 94))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel2)
                .addGap(64, 64, 64)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jcbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jcbAnio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevoGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModificarGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void armarCabeceraGastos() {

    modeloGastos.addColumn("ID");
    modeloGastos.addColumn("Fecha");
    modeloGastos.addColumn("Categoría");
    modeloGastos.addColumn("Descripción");
    modeloGastos.addColumn("Monto");
    modeloGastos.addColumn("Observación");

    TablaCompras.setModel(modeloGastos);

    TablaCompras.getColumnModel().getColumn(0).setMinWidth(0);
    TablaCompras.getColumnModel().getColumn(0).setMaxWidth(0);
    TablaCompras.getColumnModel().getColumn(0).setWidth(0);
}
    
    
    
    private void cargarCombosFecha() {

    jcbMes.removeAllItems();
    jcbAnio.removeAllItems();

    jcbMes.addItem("Todos");
    jcbMes.addItem("Enero");
    jcbMes.addItem("Febrero");
    jcbMes.addItem("Marzo");
    jcbMes.addItem("Abril");
    jcbMes.addItem("Mayo");
    jcbMes.addItem("Junio");
    jcbMes.addItem("Julio");
    jcbMes.addItem("Agosto");
    jcbMes.addItem("Septiembre");
    jcbMes.addItem("Octubre");
    jcbMes.addItem("Noviembre");
    jcbMes.addItem("Diciembre");

    jcbAnio.addItem("Todos");

    for (int anio = 2020; anio <= 2036; anio++) {
        jcbAnio.addItem(String.valueOf(anio));
    }
}
    
    
    
    
    private void seleccionarTodos() {

    jcbMes.setSelectedItem("Todos");
    jcbAnio.setSelectedItem("Todos");
}
    
    
    
    
    private int obtenerNumeroMes(String mes) {

    switch (mes) {

        case "Enero":
            return 1;

        case "Febrero":
            return 2;

        case "Marzo":
            return 3;

        case "Abril":
            return 4;

        case "Mayo":
            return 5;

        case "Junio":
            return 6;

        case "Julio":
            return 7;

        case "Agosto":
            return 8;

        case "Septiembre":
            return 9;

        case "Octubre":
            return 10;

        case "Noviembre":
            return 11;

        case "Diciembre":
            return 12;

        default:
            return 0;
    }
}
    
    
    
    
    private void cargarGastos() {

        modeloGastos.setRowCount(0);

        if (jcbMes.getSelectedItem() == null || jcbAnio.getSelectedItem() == null) {
            return;
        }

        String nombreMes = jcbMes.getSelectedItem().toString();
        String textoAnio = jcbAnio.getSelectedItem().toString();

        int mes;

        if (nombreMes.equals("Todos")) {
            mes = 0;
        } else {
            mes = obtenerNumeroMes(nombreMes);
        }

        int anio;

        if (textoAnio.equals("Todos")) {
            anio = 0;
        } else {
            anio = Integer.parseInt(textoAnio);
        }

        ArrayList<Gasto> gastos =
                gastoData.listarGastosFiltro(mes, anio);

        DateTimeFormatter formato =
                DateTimeFormatter.ofPattern("dd/MM/yyyy");

        int total = 0;

        for (Gasto gasto : gastos) {

            modeloGastos.addRow(new Object[]{
                gasto.getIdGasto(),
                gasto.getFecha().format(formato),
                gasto.getCategoria(),
                gasto.getDescripcion(),
                "$ " + gasto.getMonto(),
                gasto.getObservacion()
            });

            total += gasto.getMonto();
        }

        jtTotal.setText("$ " + total);
}
    
    
    
    private void aplicarEstiloTabla() {

        TablaCompras.setRowHeight(28);
        TablaCompras.setFont(new java.awt.Font("Segoe UI", 0, 14));

        TablaCompras.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", 1, 14)
        );

        TablaCompras.setSelectionBackground(new java.awt.Color(180, 205, 235));
        TablaCompras.setSelectionForeground(java.awt.Color.BLACK);

        TablaCompras.setGridColor(new java.awt.Color(220, 220, 220));
}
    
    
    
    private void aplicarEstiloBotones() {

    // Botones verdes - acciones positivas
    jbNuevoGasto.setBackground(new java.awt.Color(60, 130, 70));
    jbNuevoGasto.setForeground(java.awt.Color.WHITE);

    // Botones azules - acciones normales
    jbModificarGasto.setBackground(new java.awt.Color(70, 90, 120));
    jbModificarGasto.setForeground(java.awt.Color.WHITE);

    // Botones rojos - acciones delicadas
    jbAnular.setBackground(new java.awt.Color(150, 60, 60));
    jbAnular.setForeground(java.awt.Color.WHITE);

    // Botones grises - navegación
    jbMenu.setBackground(new java.awt.Color(70, 70, 70));
    jbMenu.setForeground(java.awt.Color.WHITE);
}
    
    
    
    
    private void jcbMesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbMesActionPerformed

        cargarGastos();

    }//GEN-LAST:event_jcbMesActionPerformed

    private void jcbAnioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcbAnioActionPerformed

        cargarGastos();

    }//GEN-LAST:event_jcbAnioActionPerformed

    private void TablaComprasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaComprasMouseClicked

        
    }//GEN-LAST:event_TablaComprasMouseClicked

    private void jbNuevoGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoGastoActionPerformed

        NuevoGasto nuevo = new NuevoGasto();
        nuevo.setVisible(true);

        this.dispose();
        
    }//GEN-LAST:event_jbNuevoGastoActionPerformed

    private void jbModificarGastoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarGastoActionPerformed

            int fila = TablaCompras.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un gasto para modificar.");
            return;
        }

        int idGasto = (Integer) TablaCompras.getValueAt(fila, 0);

        Gasto gasto = gastoData.buscarGastoPorId(idGasto);

        if (gasto == null) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar el gasto seleccionado.");
            return;
        }

        ModificarGasto modificar = new ModificarGasto(gasto);
        modificar.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jbModificarGastoActionPerformed

    private void jbAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularActionPerformed

            int fila = TablaCompras.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un gasto para anular.");
            return;
        }

        int idGasto = (Integer) TablaCompras.getValueAt(fila, 0);

        String fecha = TablaCompras.getValueAt(fila, 1).toString();
        String categoria = TablaCompras.getValueAt(fila, 2).toString();
        String descripcion = TablaCompras.getValueAt(fila, 3).toString();

        String montoTexto =
                TablaCompras.getValueAt(fila, 4).toString()
                .replace("$", "")
                .trim();

        int monto = Integer.parseInt(montoTexto);

        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Está seguro que desea anular este gasto?\n\n"
                + "Fecha: " + fecha + "\n"
                + "Categoría: " + categoria + "\n"
                + "Descripción: " + descripcion + "\n"
                + "Monto: $" + monto,
                "Confirmar anulación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        gastoData.anularGasto(idGasto);

        cargarGastos();

    }//GEN-LAST:event_jbAnularActionPerformed

    private void jbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuActionPerformed

        Menu menu = new Menu();
        menu.show();
        dispose();

    }//GEN-LAST:event_jbMenuActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCompras;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnular;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbModificarGasto;
    private javax.swing.JButton jbNuevoGasto;
    private javax.swing.JComboBox<String> jcbAnio;
    private javax.swing.JComboBox<String> jcbMes;
    private javax.swing.JTextField jtTotal;
    // End of variables declaration//GEN-END:variables
}
