/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Autos;

import AccesoDatos.AutoData;
import Entidades.Auto;
import Vistas.Menu;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pato
 */
public class BuscarAutos extends javax.swing.JFrame {

    
    
    
    private AutoData autoData = new AutoData();

private DefaultTableModel modeloAutos = new DefaultTableModel() {

    @Override
    public boolean isCellEditable(int fila, int columna) {
        return false;
    }
};
    
    
    
    
    
    
    public BuscarAutos() {
        initComponents();
        
        armarCabeceraAutos();
        buscarAutos();
        
        aplicarEstiloTabla();
        aplicarEstiloBotones();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Llave.png")));
        setLocationRelativeTo(null);
        this.setTitle("Autos");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaAutos = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jtPatente = new javax.swing.JTextField();
        jbNuevoAuto = new javax.swing.JButton();
        jbGestionar = new javax.swing.JButton();
        jbMenu = new javax.swing.JButton();
        jbBaja = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setText("Buscar Autos");

        TablaAutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaAutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaAutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaAutos);

        jLabel7.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(200, 200, 200));
        jLabel7.setText("Buscar Patente:");

        jtPatente.setBackground(new java.awt.Color(50, 50, 50));
        jtPatente.setForeground(new java.awt.Color(220, 220, 220));
        jtPatente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtPatenteKeyReleased(evt);
            }
        });

        jbNuevoAuto.setBackground(new java.awt.Color(5, 5, 5));
        jbNuevoAuto.setForeground(new java.awt.Color(0, 153, 204));
        jbNuevoAuto.setText("Nuevo Auto");
        jbNuevoAuto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevoAutoActionPerformed(evt);
            }
        });

        jbGestionar.setBackground(new java.awt.Color(5, 5, 5));
        jbGestionar.setForeground(new java.awt.Color(0, 153, 204));
        jbGestionar.setText("Gestionar Auto");
        jbGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionarActionPerformed(evt);
            }
        });

        jbMenu.setBackground(new java.awt.Color(5, 5, 5));
        jbMenu.setForeground(new java.awt.Color(0, 153, 204));
        jbMenu.setText("Volver al Menu");
        jbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuActionPerformed(evt);
            }
        });

        jbBaja.setBackground(new java.awt.Color(5, 5, 5));
        jbBaja.setForeground(new java.awt.Color(0, 153, 204));
        jbBaja.setText("Dar de Baja");
        jbBaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBajaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jbNuevoAuto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGap(154, 154, 154)
                            .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(180, 180, 180)
                            .addComponent(jbGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 694, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(65, 65, 65))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel2)
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jtPatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevoAuto, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBaja, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbNuevoAutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevoAutoActionPerformed

        NuevoClienteAuto nuevo = new NuevoClienteAuto();
        nuevo.setVisible(true);

        this.dispose();
        
    }//GEN-LAST:event_jbNuevoAutoActionPerformed

    private void jbGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionarActionPerformed
        
        abrirGestionAutoSeleccionado();
        
    }//GEN-LAST:event_jbGestionarActionPerformed

    private void jbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuActionPerformed
        
        Menu menu = new Menu();
        menu.setVisible(true);

        this.dispose();
        
    }//GEN-LAST:event_jbMenuActionPerformed

    private void jtPatenteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPatenteKeyReleased
        
        buscarAutos();
        
    }//GEN-LAST:event_jtPatenteKeyReleased

    
    
    private void jbBajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBajaActionPerformed
        
            int fila = TablaAutos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un auto para dar de baja.");
            return;
        }

        int idAuto = (Integer) TablaAutos.getValueAt(fila, 0);

        Auto auto = autoData.buscarAutoPorId(idAuto);

        if (auto == null) {
            JOptionPane.showMessageDialog(null, "No se pudo encontrar el auto seleccionado.");
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Está seguro que desea dar de baja este auto?\n\n"
                + "Patente: " + auto.getPatente() + "\n"
                + "Vehículo: " + auto.getVehiculo() + "\n"
                + "Cliente: " + auto.getCliente().getNombre() + "\n\n"
                + "Esta acción no borra el historial, solo oculta el auto del sistema.",
                "Confirmar baja",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        autoData.darDeBajaAuto(idAuto);

        buscarAutos();
        
    }//GEN-LAST:event_jbBajaActionPerformed

    private void TablaAutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaAutosMouseClicked
        
        if (evt.getClickCount() == 2 && TablaAutos.getSelectedRow() != -1) {

        abrirGestionAutoSeleccionado();
    }
        
    }//GEN-LAST:event_TablaAutosMouseClicked

    
    
    
    private void armarCabeceraAutos() {

    modeloAutos.addColumn("ID");
    modeloAutos.addColumn("Patente");
    modeloAutos.addColumn("Vehículo");
    modeloAutos.addColumn("Cliente");
    modeloAutos.addColumn("Teléfono");

    TablaAutos.setModel(modeloAutos);

    TablaAutos.getColumnModel().getColumn(0).setMinWidth(0);
    TablaAutos.getColumnModel().getColumn(0).setMaxWidth(0);
    TablaAutos.getColumnModel().getColumn(0).setWidth(0);
}
    
    
    
    
    private void buscarAutos() {

    modeloAutos.setRowCount(0);

    String patente = jtPatente.getText().trim();

    ArrayList<Auto> autos = autoData.buscarAutosPorPatente(patente);

    for (Auto auto : autos) {

        modeloAutos.addRow(new Object[]{
            auto.getIdAuto(),
            auto.getPatente(),
            auto.getVehiculo(),
            auto.getCliente().getNombre(),
            auto.getCliente().getTelefono()
        });
    }
}
    
    
    
    
    private void abrirGestionAutoSeleccionado() {

        int fila = TablaAutos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un auto.");
            return;
        }

        int idAuto = (Integer) TablaAutos.getValueAt(fila, 0);

        Auto auto = autoData.buscarAutoPorId(idAuto);

        if (auto == null) {
            JOptionPane.showMessageDialog(null, "No se pudo cargar el auto seleccionado.");
            return;
        }

        GestionAuto gestion = new GestionAuto(auto);
        gestion.setVisible(true);

        this.dispose();
}
    
    
    
    
    
    private void aplicarEstiloTabla() {

        TablaAutos.setRowHeight(28);
        TablaAutos.setFont(new java.awt.Font("Segoe UI", 0, 14));

        TablaAutos.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", 1, 14)
        );

        TablaAutos.setSelectionBackground(new java.awt.Color(180, 205, 235));
        TablaAutos.setSelectionForeground(java.awt.Color.BLACK);

        TablaAutos.setGridColor(new java.awt.Color(220, 220, 220));
}
    
    
    
    
    
    
    private void aplicarEstiloBotones() {


    jbNuevoAuto.setBackground(new java.awt.Color(60, 130, 70));
    jbNuevoAuto.setForeground(java.awt.Color.WHITE);


    jbGestionar.setBackground(new java.awt.Color(70, 90, 120));
    jbGestionar.setForeground(java.awt.Color.WHITE);


    jbBaja.setBackground(new java.awt.Color(150, 60, 60));
    jbBaja.setForeground(java.awt.Color.WHITE);

    jbMenu.setBackground(new java.awt.Color(70, 70, 70));
    jbMenu.setForeground(java.awt.Color.WHITE);
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaAutos;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbBaja;
    private javax.swing.JButton jbGestionar;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbNuevoAuto;
    private javax.swing.JTextField jtPatente;
    // End of variables declaration//GEN-END:variables
}
