package Vistas;

import AccesoDatos.CasaData;
import AccesoDatos.PagoData;
import Entidades.Casa;
import Entidades.Pago;
import java.awt.Toolkit;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;





public class HistorialPagos extends javax.swing.JFrame {

    
    private Casa casaActual;

    private PagoData pagoData = new PagoData();

    private DefaultTableModel modeloPagos = new DefaultTableModel() {

        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    
    
    private CasaData casaData = new CasaData();
    
    
    public HistorialPagos(Casa casa) {
        initComponents();
        this.casaActual = casa;
        armarCabeceraPagos();
        aplicarEstiloTabla();
        aplicarEstiloBotones();
        cargarDatosCasa();
        cargarPagos();
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Llave.png")));
        setLocationRelativeTo(null);
        this.setTitle("Historial Pagos");
    }

    
    
    
    
    private void cargarDatosCasa() {

        jtCasa.setText(casaActual.getNombre());
        jtSaldoActual.setText("$ " + casaActual.getSaldo());
    }

    
    
    
    
    private void armarCabeceraPagos() {

        modeloPagos.addColumn("ID");
        modeloPagos.addColumn("Fecha");
        modeloPagos.addColumn("Monto");
        modeloPagos.addColumn("Observación");

        TablaPagos.setModel(modeloPagos);

        TablaPagos.getColumnModel().getColumn(0).setMinWidth(0);
        TablaPagos.getColumnModel().getColumn(0).setMaxWidth(0);
        TablaPagos.getColumnModel().getColumn(0).setWidth(0);
    }

    
    
    
    private void cargarPagos() {

        modeloPagos.setRowCount(0);

        ArrayList<Pago> pagos =
            pagoData.listarPagosPorCasa(casaActual);

        DateTimeFormatter formato =
            DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

        for (Pago pago : pagos) {

            modeloPagos.addRow(new Object[]{
                pago.getIdPago(),
                pago.getFecha().format(formato),
                "$ " + pago.getMonto(),
                pago.getObservacion()
            });
        }
    }
    
    
    private void aplicarEstiloTabla() {

        TablaPagos.setRowHeight(28);
        TablaPagos.setFont(new java.awt.Font("Segoe UI", 0, 14));

        TablaPagos.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", 1, 14)
        );

        TablaPagos.setSelectionBackground(new java.awt.Color(180, 205, 235));
        TablaPagos.setSelectionForeground(java.awt.Color.BLACK);

        TablaPagos.setGridColor(new java.awt.Color(220, 220, 220));
}
    
    
    
    
    
    private void aplicarEstiloBotones() {

    jbAnularPago.setBackground(new java.awt.Color(150, 60, 60));
    jbAnularPago.setForeground(java.awt.Color.WHITE);

    jbVolver.setBackground(new java.awt.Color(70, 70, 70));
    jbVolver.setForeground(java.awt.Color.WHITE);
}
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtSaldoActual = new javax.swing.JTextField();
        jtCasa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaPagos = new javax.swing.JTable();
        jbVolver = new javax.swing.JButton();
        jbAnularPago = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setText("Historial de Pagos");

        jPanel2.setBackground(new java.awt.Color(60, 60, 60));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 220, 220));
        jLabel1.setText("Casa:");

        jLabel3.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 220, 220));
        jLabel3.setText("Saldo actual:");

        jtSaldoActual.setEditable(false);
        jtSaldoActual.setBackground(new java.awt.Color(50, 50, 50));
        jtSaldoActual.setForeground(new java.awt.Color(204, 204, 0));

        jtCasa.setEditable(false);
        jtCasa.setBackground(new java.awt.Color(50, 50, 50));
        jtCasa.setForeground(new java.awt.Color(220, 220, 220));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtCasa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtSaldoActual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        TablaPagos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaPagos);

        jbVolver.setBackground(new java.awt.Color(5, 5, 5));
        jbVolver.setForeground(new java.awt.Color(255, 102, 51));
        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        jbAnularPago.setBackground(new java.awt.Color(5, 5, 5));
        jbAnularPago.setForeground(new java.awt.Color(255, 0, 0));
        jbAnularPago.setText("Anular Pago");
        jbAnularPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularPagoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbAnularPago)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(66, 66, 66))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel2)
                .addGap(41, 41, 41)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAnularPago, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed

        GestionCasa gestion = new GestionCasa(casaActual);
        gestion.setVisible(true);

        this.dispose();
    }//GEN-LAST:event_jbVolverActionPerformed

    private void jbAnularPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularPagoActionPerformed

        int fila = TablaPagos.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione un pago para anular.");
            return;
        }

        int idPago = (Integer) TablaPagos.getValueAt(fila, 0);

        String fecha = TablaPagos.getValueAt(fila, 1).toString();

        String montoTexto = TablaPagos.getValueAt(fila, 2).toString()
                .replace("$", "")
                .trim();

        int monto = Integer.parseInt(montoTexto);

        String observacion = TablaPagos.getValueAt(fila, 3).toString();

        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Está seguro que desea anular este pago?\n\n"
                + "Fecha: " + fecha + "\n"
                + "Monto: $" + monto + "\n"
                + "Observación: " + observacion + "\n\n"
                + "Este importe se volverá a sumar al saldo de la casa.",
                "Confirmar anulación",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        pagoData.anularPago(idPago);

        casaData.sumarSaldo(casaActual.getIdCasa(), monto);

        JOptionPane.showMessageDialog(null, "Pago anulado correctamente.");

        Casa casaActualizada = casaData.buscarCasaPorId(casaActual.getIdCasa());

        GestionCasa gestioncasa = new GestionCasa(casaActualizada);
        gestioncasa.setVisible(true);

        this.dispose();

    }//GEN-LAST:event_jbAnularPagoActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaPagos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbAnularPago;
    private javax.swing.JButton jbVolver;
    private javax.swing.JTextField jtCasa;
    private javax.swing.JTextField jtSaldoActual;
    // End of variables declaration//GEN-END:variables
}
