/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Vistas.Autos.BuscarAutos;
import Vistas.Gastos.VerGastos;
import Vistas.Productos.GestionProductos;
import java.awt.Color;
import java.awt.Font;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;






class FondoPanel extends JPanel {

        private Image imagen;

        public FondoPanel() {
            imagen = new ImageIcon(getClass().getResource("/Imagenes/taller_fondo.jpg")).getImage();
        }

        @Override
        public void paint(Graphics g) {
            g.drawImage(imagen, 0, 0, getWidth(), getHeight(), this);

            Graphics2D g2 = (Graphics2D) g;

            // Capa oscura arriba de la imagen para que se lean bien los textos
            g2.setColor(new Color(0, 0, 0, 140));
            g2.fillRect(0, 0, getWidth(), getHeight());

            setOpaque(false);

            super.paint(g);
        }
}






public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        this.setContentPane(new FondoPanel());
        initComponents();
        
        setSize(920, 720);
        aplicarEstiloMenu();
        aplicarIconos();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Llave.png")));
        this.setLocationRelativeTo(null);
        this.setTitle("Menu");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbVerCasas = new javax.swing.JButton();
        jbSalir = new javax.swing.JButton();
        jbGastos = new javax.swing.JButton();
        jbAutos = new javax.swing.JButton();
        jbProductos = new javax.swing.JButton();
        jlTitulo = new javax.swing.JLabel();
        jlSubtitulo = new javax.swing.JLabel();
        jlPie = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        jbVerCasas.setBackground(new java.awt.Color(5, 5, 5));
        jbVerCasas.setForeground(new java.awt.Color(51, 153, 0));
        jbVerCasas.setText("Ver Casas");
        jbVerCasas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVerCasasActionPerformed(evt);
            }
        });

        jbSalir.setBackground(new java.awt.Color(153, 0, 0));
        jbSalir.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jbSalir.setForeground(new java.awt.Color(5, 5, 5));
        jbSalir.setText("Salir a Windows");
        jbSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSalirActionPerformed(evt);
            }
        });

        jbGastos.setBackground(new java.awt.Color(5, 5, 5));
        jbGastos.setForeground(new java.awt.Color(51, 153, 0));
        jbGastos.setText("Gastos Taller");
        jbGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGastosActionPerformed(evt);
            }
        });

        jbAutos.setBackground(new java.awt.Color(5, 5, 5));
        jbAutos.setForeground(new java.awt.Color(51, 153, 0));
        jbAutos.setText("Ver Autos");
        jbAutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAutosActionPerformed(evt);
            }
        });

        jbProductos.setBackground(new java.awt.Color(5, 5, 5));
        jbProductos.setForeground(new java.awt.Color(51, 153, 0));
        jbProductos.setText("Productos");
        jbProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbProductosActionPerformed(evt);
            }
        });

        jlTitulo.setText("ARANDA AUTOMECÁNICA");

        jlSubtitulo.setText("Sistema de gestión del taller");

        jlPie.setText("Seleccione una opción para continuar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbAutos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbVerCasas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbGastos, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                            .addComponent(jbSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(297, 297, 297)
                        .addComponent(jlSubtitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(193, 193, 193)
                        .addComponent(jlTitulo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(294, 294, 294)
                        .addComponent(jlPie)))
                .addGap(248, 254, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jlSubtitulo)
                .addGap(42, 42, 42)
                .addComponent(jbAutos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbVerCasas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbGastos, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 124, Short.MAX_VALUE)
                .addComponent(jlPie)
                .addGap(39, 39, 39))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbVerCasasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVerCasasActionPerformed
        
        VerCasas vercasas = new VerCasas();
        vercasas.show();
        dispose();
        
    }//GEN-LAST:event_jbVerCasasActionPerformed

    private void jbSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSalirActionPerformed

        int opcion = JOptionPane.showConfirmDialog(null,
            "¿Está seguro de que desea salir del Programa?",
            "Confirmación",
            JOptionPane.OK_CANCEL_OPTION);

        if (opcion == JOptionPane.OK_OPTION) {
            dispose(); // Cierra la ventana
            System.exit(0);
        }
    }//GEN-LAST:event_jbSalirActionPerformed

    private void jbGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGastosActionPerformed
        
        VerGastos vergastos = new VerGastos();
        vergastos.show();
        dispose();
        
    }//GEN-LAST:event_jbGastosActionPerformed

    private void jbAutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAutosActionPerformed
        
        BuscarAutos verautos = new BuscarAutos();
        verautos.show();
        dispose();
        
    }//GEN-LAST:event_jbAutosActionPerformed

    private void jbProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbProductosActionPerformed
        
        GestionProductos ges = new GestionProductos();
        ges.show();
        dispose();
        
    }//GEN-LAST:event_jbProductosActionPerformed

    
    
    
    private void aplicarEstiloMenu() {

        // Fondo transparente para que se vea la imagen
        getContentPane().setBackground(new Color(0, 0, 0, 0));
        jPanel1.setOpaque(false);

        // Labels
        jlTitulo.setForeground(Color.WHITE);
        jlTitulo.setFont(new Font("Segoe UI", Font.BOLD, 42));
        jlTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlSubtitulo.setForeground(new Color(130, 190, 255));
        jlSubtitulo.setFont(new Font("Segoe UI", Font.BOLD, 22));
        jlSubtitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jlPie.setForeground(Color.WHITE);
        jlPie.setFont(new Font("Segoe UI", Font.ITALIC, 18));
        jlPie.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        // Botones principales
        estiloBotonMenu(jbAutos);
        estiloBotonMenu(jbProductos);
        estiloBotonMenu(jbVerCasas);
        estiloBotonMenu(jbGastos);

        // Botón salir
        jbSalir.setBackground(new Color(180, 40, 40));
        jbSalir.setForeground(Color.WHITE);
        jbSalir.setFont(new Font("Segoe UI", Font.BOLD, 20));
        jbSalir.setFocusPainted(false);
        jbSalir.setOpaque(true);
        
        acomodarComponentes();
}
    
    
    
    private void acomodarComponentes() {

    int anchoVentana = getWidth();

    int anchoTitulo = 700;
    int altoTitulo = 55;

    int anchoSubtitulo = 500;
    int altoSubtitulo = 35;

    int anchoBoton = 420;
    int altoBoton = 62;

    int xTitulo = (anchoVentana - anchoTitulo) / 2;
    int xSubtitulo = (anchoVentana - anchoSubtitulo) / 2;
    int xBoton = (anchoVentana - anchoBoton) / 2;

    jlTitulo.setBounds(xTitulo, 35, anchoTitulo, altoTitulo);
    jlSubtitulo.setBounds(xSubtitulo, 95, anchoSubtitulo, altoSubtitulo);

    jbAutos.setBounds(xBoton, 170, anchoBoton, altoBoton);
    jbProductos.setBounds(xBoton, 245, anchoBoton, altoBoton);
    jbVerCasas.setBounds(xBoton, 320, anchoBoton, altoBoton);
    jbGastos.setBounds(xBoton, 395, anchoBoton, altoBoton);
    jbSalir.setBounds(xBoton, 470, anchoBoton, altoBoton);

    jlPie.setBounds(0, 610, anchoVentana, 35);
}
    
    
    
    private void estiloBotonMenu(JButton boton) {

    boton.setBackground(new Color(180, 180, 180));
    boton.setForeground(new Color(20, 35, 55));
    boton.setFont(new Font("Segoe UI", Font.BOLD, 22));
    boton.setFocusPainted(false);
    boton.setOpaque(true);
}
    
    
    
    private void aplicarIconos() {

        jbAutos.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Iconos/auto.png")));
        jbProductos.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Iconos/filtro.png")));
        jbVerCasas.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Iconos/casa.png")));
        jbGastos.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Iconos/gasto.png")));
        jbSalir.setIcon(new ImageIcon(getClass().getResource("/Imagenes/Iconos/salir.png")));

        configurarBotonConIcono(jbAutos);
        configurarBotonConIcono(jbProductos);
        configurarBotonConIcono(jbVerCasas);
        configurarBotonConIcono(jbGastos);
        configurarBotonConIcono(jbSalir);
}
    
    
    
    private void configurarBotonConIcono(javax.swing.JButton boton) {

        boton.setHorizontalAlignment(SwingConstants.LEFT);
        boton.setHorizontalTextPosition(SwingConstants.RIGHT);
        boton.setVerticalTextPosition(SwingConstants.CENTER);

        boton.setIconTextGap(35);
}
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbAutos;
    private javax.swing.JButton jbGastos;
    private javax.swing.JButton jbProductos;
    private javax.swing.JButton jbSalir;
    private javax.swing.JButton jbVerCasas;
    private javax.swing.JLabel jlPie;
    private javax.swing.JLabel jlSubtitulo;
    private javax.swing.JLabel jlTitulo;
    // End of variables declaration//GEN-END:variables
}
