package Vistas;

import javax.swing.table.DefaultTableModel;
import AccesoDatos.CasaData;
import Entidades.Casa;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Pato
 */
public class VerCasas extends javax.swing.JFrame {

    private DefaultTableModel modeloCasas = new DefaultTableModel() {

    @Override
    public boolean isCellEditable(int fila, int columna) {
        return false;
    }
};
    
    CasaData casaData = new CasaData();
    
    public VerCasas() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Ver Casas");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Llave.png")));
        armarCabecera();
        llenarTablaCasas();
        aplicarEstiloTabla();
        aplicarEstiloBotones();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaCasas = new javax.swing.JTable();
        jbNuevaCasa = new javax.swing.JButton();
        jbModificar = new javax.swing.JButton();
        jbGestionar = new javax.swing.JButton();
        jbEliminar = new javax.swing.JButton();
        jbMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 42)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setText("Casas de Repuestos");

        TablaCasas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaCasas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaCasasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaCasas);

        jbNuevaCasa.setBackground(new java.awt.Color(5, 5, 5));
        jbNuevaCasa.setForeground(new java.awt.Color(51, 153, 0));
        jbNuevaCasa.setText("Nueva Casa");
        jbNuevaCasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbNuevaCasaActionPerformed(evt);
            }
        });

        jbModificar.setBackground(new java.awt.Color(5, 5, 5));
        jbModificar.setForeground(new java.awt.Color(51, 153, 0));
        jbModificar.setText("Modificar Casa");
        jbModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbModificarActionPerformed(evt);
            }
        });

        jbGestionar.setBackground(new java.awt.Color(5, 5, 5));
        jbGestionar.setForeground(new java.awt.Color(51, 153, 0));
        jbGestionar.setText("Gestionar Casa");
        jbGestionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGestionarActionPerformed(evt);
            }
        });

        jbEliminar.setBackground(new java.awt.Color(5, 5, 5));
        jbEliminar.setForeground(new java.awt.Color(51, 153, 0));
        jbEliminar.setText("Eliminar");
        jbEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEliminarActionPerformed(evt);
            }
        });

        jbMenu.setBackground(new java.awt.Color(5, 5, 5));
        jbMenu.setForeground(new java.awt.Color(255, 102, 0));
        jbMenu.setText("Volver al Menu");
        jbMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jbMenu)
                .addGap(27, 27, 27))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jbNuevaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jbModificar)
                        .addGap(65, 65, 65)
                        .addComponent(jbGestionar)
                        .addGap(73, 73, 73)
                        .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(141, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(247, 247, 247))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel2)
                .addGap(61, 61, 61)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbNuevaCasa, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbGestionar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addComponent(jbMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    private void aplicarEstiloTabla() {

        TablaCasas.setRowHeight(28);
        TablaCasas.setFont(new java.awt.Font("Segoe UI", 0, 14));

        TablaCasas.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", 1, 14)
        );

        TablaCasas.setSelectionBackground(new java.awt.Color(180, 205, 235));
        TablaCasas.setSelectionForeground(java.awt.Color.BLACK);

        TablaCasas.setGridColor(new java.awt.Color(220, 220, 220));
}
    
    
    
    private void aplicarEstiloBotones() {

        jbNuevaCasa.setBackground(new java.awt.Color(60, 130, 70));
        jbNuevaCasa.setForeground(java.awt.Color.WHITE);

        jbModificar.setBackground(new java.awt.Color(70, 90, 120));
        jbModificar.setForeground(java.awt.Color.WHITE);

        jbGestionar.setBackground(new java.awt.Color(70, 90, 120));
        jbGestionar.setForeground(java.awt.Color.WHITE);

        jbEliminar.setBackground(new java.awt.Color(150, 60, 60));
        jbEliminar.setForeground(java.awt.Color.WHITE);

        jbMenu.setBackground(new java.awt.Color(70, 70, 70));
        jbMenu.setForeground(java.awt.Color.WHITE);
}
    
    
    
    
    private void abrirGestionCasaSeleccionada() {

    int fila = TablaCasas.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione una casa.");
        return;
    }

    int idCasa = (Integer) TablaCasas.getValueAt(fila, 0);

    Casa casa = casaData.buscarCasaPorId(idCasa);

    if (casa == null) {
        JOptionPane.showMessageDialog(null, "No se pudo cargar la casa seleccionada.");
        return;
    }

    GestionCasa gestion = new GestionCasa(casa);
    gestion.setVisible(true);

    this.dispose();
}
    
    
    
    
    private void jbNuevaCasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbNuevaCasaActionPerformed

        NuevaCasa nuevacasa = new NuevaCasa();
        nuevacasa.show();
        dispose();

    }//GEN-LAST:event_jbNuevaCasaActionPerformed

    private void jbModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbModificarActionPerformed
        
        int fila = TablaCasas.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(null, "Seleccione una casa.");
        return;
    }

    int idCasa = (Integer) TablaCasas.getValueAt(fila, 0);

    Casa casa = casaData.buscarCasaPorId(idCasa);

    if (casa == null) {
        JOptionPane.showMessageDialog(null, "No se pudo cargar la casa seleccionada.");
        return;
    }

    ModificarCasa modificar = new ModificarCasa(casa);
    modificar.setVisible(true);

    this.dispose();
        
    }//GEN-LAST:event_jbModificarActionPerformed

    private void jbGestionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGestionarActionPerformed
        
        abrirGestionCasaSeleccionada();
        
    }//GEN-LAST:event_jbGestionarActionPerformed

    private void jbEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEliminarActionPerformed
        
            int fila = TablaCasas.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una casa para eliminar.");
            return;
        }

        int idCasa = (Integer) TablaCasas.getValueAt(fila, 0);

        Casa casa = casaData.buscarCasaPorId(idCasa);

        if (casa == null) {
            JOptionPane.showMessageDialog(null, "No se pudo encontrar la casa seleccionada.");
            return;
        }

        if (casa.getSaldo() > 0) {
            JOptionPane.showMessageDialog(
                null,
                "No se puede eliminar esta casa porque tiene saldo pendiente.\n\n"
                + "Saldo actual: $" + casa.getSaldo()
            );
            return;
        }

        int opcion = JOptionPane.showConfirmDialog(
            null,
            "¿Está seguro que desea eliminar la casa?\n\n"
            + "Casa: " + casa.getNombre() + "\n"
            + "Esta acción no borrará el historial, solo la ocultará del sistema.",
            "Confirmar eliminación",
            JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        casaData.desactivarCasa(idCasa);

        llenarTablaCasas();
        
    }//GEN-LAST:event_jbEliminarActionPerformed

    private void jbMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbMenuActionPerformed
        
        Menu menu = new Menu();
        menu.show();
        dispose();
        
    }//GEN-LAST:event_jbMenuActionPerformed

    private void TablaCasasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaCasasMouseClicked
        
            if (evt.getClickCount() == 2 && TablaCasas.getSelectedRow() != -1) {

            abrirGestionCasaSeleccionada();
        }
        
    }//GEN-LAST:event_TablaCasasMouseClicked

    
    
    
    
    private void llenarTablaCasas() {

    modeloCasas.setRowCount(0);

    ArrayList<Casa> lista = casaData.listarCasas();

    for (Casa casa : lista) {
        modeloCasas.addRow(new Object[]{casa.getIdCasa(), casa.getNombre(), casa.getTelefono(), "$ " + casa.getSaldo()});
    }
}
    
    
    
    
    
    private void armarCabecera() {

    modeloCasas.addColumn("ID");
    modeloCasas.addColumn("Nombre");
    modeloCasas.addColumn("Teléfono");
    modeloCasas.addColumn("Saldo");

    TablaCasas.setModel(modeloCasas);

    TablaCasas.getColumnModel().getColumn(0).setMinWidth(0);
    TablaCasas.getColumnModel().getColumn(0).setMaxWidth(0);
    TablaCasas.getColumnModel().getColumn(0).setWidth(0);
}
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaCasas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEliminar;
    private javax.swing.JButton jbGestionar;
    private javax.swing.JButton jbMenu;
    private javax.swing.JButton jbModificar;
    private javax.swing.JButton jbNuevaCasa;
    // End of variables declaration//GEN-END:variables
}
