/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas.Productos;

import AccesoDatos.VentaProductoData;
import Entidades.DetalleVentaProducto;
import Entidades.VentaProducto;
import java.awt.Toolkit;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pato
 */
public class HistorialVentasProductos extends javax.swing.JFrame {

    
        private VentaProductoData ventaProductoData = new VentaProductoData();

    private DefaultTableModel modeloVentas = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };

    private DefaultTableModel modeloDetalle = new DefaultTableModel() {
        @Override
        public boolean isCellEditable(int fila, int columna) {
            return false;
        }
    };
    
    
    
    public HistorialVentasProductos() {
        initComponents();

        armarCabeceraVentas();
        armarCabeceraDetalle();

        cargarVentas();

        aplicarEstiloTablas();
        aplicarEstiloBotones();

        setLocationRelativeTo(null);
        this.setTitle("Historial de Ventas");
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Imagenes/Llave.png")));
    
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaVentas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaDetalle = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jbAnular = new javax.swing.JButton();
        jbVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(50, 50, 50));

        jLabel2.setFont(new java.awt.Font("Viner Hand ITC", 1, 38)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(230, 230, 230));
        jLabel2.setText("Historial");

        TablaVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaVentasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaVentas);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 22)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(220, 220, 220));
        jLabel1.setText("Ventas:");

        TablaDetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaDetalle);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(220, 220, 220));
        jLabel3.setText("Detalle de venta seleccionada:");

        jbAnular.setBackground(new java.awt.Color(5, 5, 5));
        jbAnular.setForeground(new java.awt.Color(0, 153, 204));
        jbAnular.setText("Anular");
        jbAnular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbAnularActionPerformed(evt);
            }
        });

        jbVolver.setBackground(new java.awt.Color(5, 5, 5));
        jbVolver.setForeground(new java.awt.Color(0, 153, 204));
        jbVolver.setText("Volver");
        jbVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(266, 266, 266)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 615, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 520, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jbAnular, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbAnular, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbAnularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbAnularActionPerformed

            int fila = TablaVentas.getSelectedRow();

        if (fila == -1) {
            JOptionPane.showMessageDialog(null, "Seleccione una venta.");
            return;
        }

        int idVenta = Integer.parseInt(TablaVentas.getValueAt(fila, 0).toString());
        String fecha = TablaVentas.getValueAt(fila, 1).toString();
        String total = TablaVentas.getValueAt(fila, 2).toString();

        int opcion = JOptionPane.showConfirmDialog(
                null,
                "¿Desea anular esta venta?\n\n"
                + "Fecha: " + fecha + "\n"
                + "Total: $ " + total + "\n\n"
                + "Se devolverá el stock de los productos vendidos.",
                "Anular venta",
                JOptionPane.YES_NO_OPTION
        );

        if (opcion != JOptionPane.YES_OPTION) {
            return;
        }

        ventaProductoData.devolverStockDeVenta(idVenta);
        ventaProductoData.anularVentaProducto(idVenta);

        JOptionPane.showMessageDialog(null, "Venta anulada correctamente.");

        cargarVentas();
        
    }//GEN-LAST:event_jbAnularActionPerformed

    private void jbVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbVolverActionPerformed
        
        GestionProductos gestion = new GestionProductos();
        gestion.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jbVolverActionPerformed

    private void TablaVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaVentasMouseClicked
        
        cargarDetalleVentaSeleccionada();
        
    }//GEN-LAST:event_TablaVentasMouseClicked

    
    
    
    private void armarCabeceraVentas() {

    modeloVentas.addColumn("ID");
    modeloVentas.addColumn("Fecha");
    modeloVentas.addColumn("Total");

    TablaVentas.setModel(modeloVentas);

    TablaVentas.getColumnModel().getColumn(0).setMinWidth(0);
    TablaVentas.getColumnModel().getColumn(0).setMaxWidth(0);
    TablaVentas.getColumnModel().getColumn(0).setWidth(0);
}
    
    
    
    
    private void armarCabeceraDetalle() {

    modeloDetalle.addColumn("Cantidad");
    modeloDetalle.addColumn("Producto");
    modeloDetalle.addColumn("Precio Unit.");
    modeloDetalle.addColumn("Total");

    TablaDetalle.setModel(modeloDetalle);
}
    
    
    
    
    private void cargarVentas() {

    modeloVentas.setRowCount(0);
    modeloDetalle.setRowCount(0);

    ArrayList<VentaProducto> ventas = ventaProductoData.listarVentasProducto();

    DateTimeFormatter formato = DateTimeFormatter.ofPattern("dd/MM/yyyy HH:mm");

    for (VentaProducto venta : ventas) {

        modeloVentas.addRow(new Object[]{
            venta.getIdVenta(),
            venta.getFecha().format(formato),
            venta.getTotal()
        });
    }
}
    
    
    
    
    
    private void cargarDetalleVenta(int idVenta) {

    modeloDetalle.setRowCount(0);

    ArrayList<DetalleVentaProducto> detalles = ventaProductoData.obtenerDetalleVentaProducto(idVenta);

    for (DetalleVentaProducto detalle : detalles) {

        String nombreProducto = "";

        if (detalle.getProducto() != null) {
            nombreProducto = detalle.getProducto().getNombre();
        }

        modeloDetalle.addRow(new Object[]{
            detalle.getCantidad(),
            nombreProducto,
            detalle.getPrecioUnitario(),
            detalle.getSubtotal()
        });
    }
}
    
     
    
    
    private void cargarDetalleVentaSeleccionada() {

    int fila = TablaVentas.getSelectedRow();

    if (fila == -1) {
        return;
    }

    int idVenta = Integer.parseInt(TablaVentas.getValueAt(fila, 0).toString());

    cargarDetalleVenta(idVenta);
}
    
    
    
    private void aplicarEstiloTablas() {

        TablaVentas.setRowHeight(28);
        TablaVentas.setFont(new java.awt.Font("Segoe UI", 0, 14));
        TablaVentas.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 14));
        TablaVentas.setSelectionBackground(new java.awt.Color(180, 205, 235));
        TablaVentas.setSelectionForeground(java.awt.Color.BLACK);
        TablaVentas.setGridColor(new java.awt.Color(220, 220, 220));

        TablaDetalle.setRowHeight(28);
        TablaDetalle.setFont(new java.awt.Font("Segoe UI", 0, 14));
        TablaDetalle.getTableHeader().setFont(new java.awt.Font("Segoe UI", 1, 14));
        TablaDetalle.setSelectionBackground(new java.awt.Color(180, 205, 235));
        TablaDetalle.setSelectionForeground(java.awt.Color.BLACK);
        TablaDetalle.setGridColor(new java.awt.Color(220, 220, 220));
}
    
    
    
    
    private void aplicarEstiloBotones() {

    // Botones rojos - acciones delicadas
    jbAnular.setBackground(new java.awt.Color(150, 60, 60));
    jbAnular.setForeground(java.awt.Color.WHITE);

    // Botones grises - navegación
    jbVolver.setBackground(new java.awt.Color(70, 70, 70));
    jbVolver.setForeground(java.awt.Color.WHITE);
}
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDetalle;
    private javax.swing.JTable TablaVentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jbAnular;
    private javax.swing.JButton jbVolver;
    // End of variables declaration//GEN-END:variables
}
